version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on: 
      - db
    networks:
      kafka_rede_kafka:

  db:
    image: mongo:6-jammy
    container_name: mongo-ms1
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      kafka_rede_kafka:

volumes:
  dbdata6:

networks:
  kafka_rede_kafka:
    external: true